Auth:
  App\Services\Interfaces\AuthenticationServiceInterface:
    - App\Services\AuthenticationPassport

App:
  App\Repositories\Interfaces\ArticleRepository:
      - App\Repositories\ArticleRepositoryImpl
  App\Services\Interfaces\ArticleService:
      - App\Services\ArticleServiceImpl
  App\Repositories\Interfaces\ClientRepository:
      - App\Repositories\ClientRepositoryImpl
  App\Services\Interfaces\ClientService:
      - App\Services\ClientServiceImpl
  clientrepositoryfacade:
      - App\Repositories\ClientRepositoryImpl
  clientservicefacade:
      - App\Services\ClientServiceImpl
  uploadphoto:
    - App\Services\UploadToS3ServiceImpl
  carte:
    - App\Services\CartePDFServiceImpl
  App\Services\Interfaces\DetteService:
    - App\Services\DetteServiceImpl
  App\Repositories\Interfaces\DetteRepository:
    - App\Repositories\DetteRepositoryImpl
